FROM python:3.12-slim

WORKDIR /app

COPY utility/monthly_cold_freezer/requirements.txt /tmp/monthly_cold_freezer_requirements.txt
RUN pip install --no-cache-dir -r /tmp/monthly_cold_freezer_requirements.txt

COPY utility/slack_msg_sender.py /app/utility/slack_msg_sender.py
COPY utility/monthly_cold_freezer /app/utility/monthly_cold_freezer

ENV PYTHONPATH=/app/utility

CMD ["python", "-m", "monthly_cold_freezer.batch"]
