name: deploy azure sps files to lambda
on:
  push:
    branches:
      - 'main'
    paths:
      - 'collector/spot-dataset/azure/lambda/current_collector/load_price.py'
      - 'collector/spot-dataset/azure/lambda/current_collector/upload_data.py'
      - 'collector/spot-dataset/azure/lambda/current_collector/lambda_function_sps.py'
      - 'collector/spot-dataset/azure/lambda/current_collector/load_sps.py'
      - 'const_config.py'
      - 'collector/spot-dataset/azure/lambda/current_collector/utill/**'
      - 'collector/spot-dataset/azure/lambda/current_collector/sps_module/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.SPOTRANK_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SPOTRANK_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-2'

jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: Zip Lambda function code
        run: |
          rm -f azure_sps_lambda.zip
          zip -j azure_sps_lambda.zip \
          ./collector/spot-dataset/azure/lambda/current_collector/load_price.py \
          ./collector/spot-dataset/azure/lambda/current_collector/upload_data.py \
          ./collector/spot-dataset/azure/lambda/current_collector/lambda_function_sps.py \
          ./collector/spot-dataset/azure/lambda/current_collector/load_sps.py \
          ./const_config.py

          cd ./collector/spot-dataset/azure/lambda/current_collector/
          zip -r azure_sps_lambda.zip ./utill/*
          zip -r azure_sps_lambda.zip ./sps_module/*
          cd ../../../../../
          mv ./collector/spot-dataset/azure/lambda/current_collector/azure_sps_lambda.zip ./

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name azure-sps-collector --zip-file fileb://azure_sps_lambda.zip