name: deploy azure files to lambda
on:
  push:
    branches:
      - 'main'
    paths:
      - 'collector/spot-dataset/azure/lambda/current_collector/utill/**'
      - 'collector/spot-dataset/azure/lambda/current_collector/compare_data.py'
      - 'collector/spot-dataset/azure/lambda/current_collector/lambda_function.py'
      - 'collector/spot-dataset/azure/lambda/current_collector/load_if.py'
      - 'collector/spot-dataset/azure/lambda/current_collector/load_price.py'
      - 'collector/spot-dataset/azure/lambda/current_collector/merge_df.py'
      - 'collector/spot-dataset/azure/lambda/current_collector/upload_data.py'
      - 'const_config.py'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.SPOTRANK_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SPOTRANK_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-2'

jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: Zip Lambda function code
        run: |
          zip -j azure_lambda.zip \
            collector/spot-dataset/azure/lambda/current_collector/compare_data.py \
            collector/spot-dataset/azure/lambda/current_collector/lambda_function.py \
            collector/spot-dataset/azure/lambda/current_collector/load_if.py \
            collector/spot-dataset/azure/lambda/current_collector/load_price.py \
            collector/spot-dataset/azure/lambda/current_collector/merge_df.py \
            collector/spot-dataset/azure/lambda/current_collector/upload_data.py \
            const_config.py
          
          zip -r azure_lambda.zip collector/spot-dataset/azure/lambda/current_collector/utill

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name azure-collector --zip-file fileb://azure_lambda.zip