name: Sync Demo-Web html to S3

on:
  push:
    branches:
      - 'main'
    paths:
      - 'frontend/public/**'
  workflow_dispatch:
      
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-2'
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Sync with AWS S3"
        run: aws s3 sync ./frontend/public/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --acl public-read --delete
